workflows:
  ios-test:
    name: NovaHR iPhone Test

    instance_type: mac_mini_m2
    max_build_duration: 30

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Flutter clean
        script: |
          flutter clean

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign

      - name: Create NovaHR IPA
        script: |
          rm -rf Payload
          rm -f NovaHR.ipa

          mkdir Payload

          cp -R build/ios/iphoneos/Runner.app Payload/

          zip -r NovaHR.ipa Payload

          echo "IPA CREATED:"
          ls -lh NovaHR.ipa

    artifacts:
      - NovaHR.ipa
      - build/ios/iphoneos/Runner.app